name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.18.5
          - 1.19
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build & Test
        run: |
          go test -race -v ./...
